INSERT INTO USERROLE ( USERROLE) values ('Manager');
INSERT INTO USERROLE ( USERROLE) values ('Player');
/
INSERT INTO AddressType ( AddressType) values ('Residential');
INSERT INTO AddressType ( AddressType) values ('Mailing');
/
INSERT INTO PaymentType ( PaymentType) values ('Visa');
INSERT INTO PaymentType ( PaymentType) values ('Discover');
/

Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'BILL','Password' ,'Email@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Manager') from dual;
Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'Todd','Password' ,'Tmail@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Manager') from dual;
Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'Harry','Password' ,'Hmail@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Manager') from dual;
Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'Jane','Password' ,'Jmail@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Player') from dual;
Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'Brian','Password' ,'Pmail@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Player') from dual;
Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'Artem','Password' ,'Amail@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Player') from dual;
Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'Abhijit','Password' ,'Imail@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Player') from dual;
Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'Chrissy','Password' ,'Cmail@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Player') from dual;
Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'Jim','Password' ,'a@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Player') from dual;
Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'John','Password' ,'b@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Player') from dual;
Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'Sally','Password' ,'c@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Player') from dual;
Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'JJ','Password' ,'d@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Player') from dual;
Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'Sarah','Password' ,'e@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Player') from dual;
Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'Sara','Password' ,'f@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Player') from dual;
Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'TJ','Password' ,'g@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Player') from dual;
Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'Jack','Password' ,'h@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Player') from dual;
Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'Phil','Password' ,'i@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Player') from dual;
Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'Miles','Password' ,'j@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Player') from dual;
Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'Rick','Password' ,'k@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Player') from dual;
Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'Carl','Password' ,'l@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Player') from dual;
Insert Into Users (Username, Passw, EMAIL, USERROLE) Select 'Lilly','Password' ,'m@Gmail.com',(select RoleID From USERROLE where USERROLE = 'Player') from dual;
/
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '2535 Fox Hill Rd','APT 1','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Residential') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '2535 Fox Hill Rd','APT 1','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Mailing') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '2535 Fox Hill Rd','APT 1','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Residential') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '2535 Fox Hill Rd','APT 1','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Mailing') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '2535 Fox Hill Rd','APT 1','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Residential') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '2535 Fox Hill Rd','APT 1','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Mailing') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '679 Waupelani Dr','APT 1','State College', 'PA','16801',(select AddressTypeID From AddressType where AddressType = 'Residential') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '679 Waupelani Dr','APT 1','State College', 'PA','16801',(select AddressTypeID From AddressType where AddressType = 'Mailing') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '679 Waupelani Dr','APT 2','State College', 'PA','16801',(select AddressTypeID From AddressType where AddressType = 'Residential') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '679 Waupelani Dr','APT 2','State College', 'PA','16801',(select AddressTypeID From AddressType where AddressType = 'Mailing') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '679 Waupelani Dr','APT 3','State College', 'PA','16801',(select AddressTypeID From AddressType where AddressType = 'Residential') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '679 Waupelani Dr','APT 4','State College', 'PA','16801',(select AddressTypeID From AddressType where AddressType = 'Mailing') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '24 Waupelani Dr','APT 1','State College', 'PA','16801',(select AddressTypeID From AddressType where AddressType = 'Residential') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '24 Waupelani Dr','APT 1','State College', 'PA','16801',(select AddressTypeID From AddressType where AddressType = 'Mailing') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '24 Waupelani Dr','APT 2','State College', 'PA','16801',(select AddressTypeID From AddressType where AddressType = 'Residential') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '24 Waupelani Dr','APT 2','State College', 'PA','16801',(select AddressTypeID From AddressType where AddressType = 'Mailing') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '24 Waupelani Dr','APT 3','State College', 'PA','16801',(select AddressTypeID From AddressType where AddressType = 'Residential') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '24 Waupelani Dr','APT 3','State College', 'PA','16801',(select AddressTypeID From AddressType where AddressType = 'Mailing') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '24 Waupelani Dr','APT 4','State College', 'PA','16801',(select AddressTypeID From AddressType where AddressType = 'Residential') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '24 Waupelani Dr','APT 4','State College', 'PA','16801',(select AddressTypeID From AddressType where AddressType = 'Mailing') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '348 Blue Course Dr','APT 1','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Residential') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '348 Blue Course Dr','APT 1','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Mailing') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '348 Blue Course Dr','APT 2','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Residential') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '348 Blue Course Dr','APT 2','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Mailing') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '348 Blue Course Dr','APT 3','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Residential') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '348 Blue Course Dr','APT 3','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Mailing') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '348 Blue Course Dr','APT 4','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Residential') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '348 Blue Course Dr','APT 5','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Mailing') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '1013 S Allen St','APT 1','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Residential') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '1013 S Allen St','APT 1','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Mailing') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '1013 S Allen St','APT 2','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Residential') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '1013 S Allen St','APT 2','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Mailing') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '1013 S Allen St','APT 3','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Residential') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '1013 S Allen St','APT 3','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Mailing') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '1013 S Allen St','APT 4','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Residential') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '1013 S Allen St','APT 4','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Mailing') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '1013 S Allen St','APT 5','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Residential') From dual;
INSERT INTO ADDRESS (    LINE1,    LINE2,    CITY,    STATE,    ZIP,    ADDRESSTYPE  ) Select '1013 S Allen St','APT 5','State College', 'PA','16803',(select AddressTypeID From AddressType where AddressType = 'Mailing') From dual;
